"""phase7 safety events

Revision ID: ac6b03bffe7e
Revises: 70de8223fc6f
Create Date: 2026-09-22 03:23:59.583989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac6b03bffe7e'
down_revision: Union[str, None] = '70de8223fc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also proposed dropping knowledge_chunks_embedding_hnsw_idx — that
    # index was created via raw SQL in the Phase 5 migration (not declared on the SQLAlchemy
    # Vector column), so autogenerate can't see it and thinks it shouldn't exist. Deliberately
    # NOT dropping it here; it stays in place.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_events')
    # ### end Alembic commands ###
