"""phase3 symptoms table

Revision ID: afa1e63a3295
Revises: 65e628e73d61
Create Date: 2026-09-21 01:34:30.537542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.encrypted_types


revision: str = 'afa1e63a3295'
down_revision: Union[str, None] = '65e628e73d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('symptom', app.db.encrypted_types.EncryptedString(), nullable=False),
    sa.Column('onset', app.db.encrypted_types.EncryptedString(), nullable=True),
    sa.Column('duration', app.db.encrypted_types.EncryptedString(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('frequency', app.db.encrypted_types.EncryptedString(), nullable=True),
    sa.Column('location', app.db.encrypted_types.EncryptedString(), nullable=True),
    sa.Column('progression', app.db.encrypted_types.EncryptedString(), nullable=True),
    sa.Column('triggers', app.db.encrypted_types.EncryptedString(), nullable=True),
    sa.Column('relieving_factors', app.db.encrypted_types.EncryptedString(), nullable=True),
    sa.Column('associated_symptoms', app.db.encrypted_types.EncryptedString(), nullable=True),
    sa.Column('certainty', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptoms')
    # ### end Alembic commands ###
